def obtener_palabras() -> list[str]:
    return [
        "cama", "perro", "gato", "auto", "casa", "arbol", "libro", "computadora",
        "teclado", "mouse", "pantalla", "cable", "disco", "memoria", "procesador",
        "placa", "fuente", "gabinete", "auricular", "parlante", "telefono", "celular",
        "reloj", "camara", "lampara", "silla", "mesa", "puerta", "ventana", "pared",
        "piso", "techo", "cocina", "baño", "dormitorio", "living", "patio", "garage",
        "jardin", "balcon", "calle", "avenida", "vereda", "plaza", "parque", "bosque",
        "selva", "desierto", "montaña", "playa", "oceano", "mar", "rio", "lago",
        "laguna", "arroyo", "cascada", "puente", "tunel", "estacion", "tren", "avion",
        "barco", "subte", "colectivo", "bicicleta", "moto", "camion", "camioneta",
        "grua", "cohete", "satelite", "planeta", "estrella", "galaxia", "universo",
        "espacio", "astronauta", "cometa", "asteroide", "sol", "luna", "tierra",
        "marte", "jupiter", "saturno", "urano", "neptuno", "pluton", "mercurio",
        "venus", "madera", "metal", "plastico", "vidrio", "papel", "carton",
        "cemento", "ladrillo", "piedra", "arena", "agua", "fuego", "aire", "viento",
        "lluvia", "nieve", "granizo", "tormenta", "trueno", "relampago", "nube",
        "niebla", "humo", "ceniza", "carbon", "petroleo", "gas", "energia",
        "electricidad", "iman", "brujula", "mapa", "globo", "espejo", "bruja",
        "mago", "duende", "fantasma", "monstruo", "dragon", "vampiro", "zombi",
        "esqueleto", "calavera", "tumba", "castillo", "palacio", "templo", "iglesia",
        "museo", "teatro", "cine", "estadio", "gimnasio", "escuela", "colegio",
        "universidad",
    ]
